
import { Word, ConjugationDrill } from './types';

export const PASSE_COMPOSE_DRILLS: ConjugationDrill[] = [
  { id: 'pc1', verb: 'Manger', subject: 'Je', conjugated: "J'ai mangé", translation: "I ate / I have eaten", auxiliary: 'ai', participle: 'mangé', ruleNote: "Uses 'avoir' + -é" },
  { id: 'pc2', verb: 'Boire', subject: 'Tu', conjugated: "Tu as bu", translation: "You drank", auxiliary: 'as', participle: 'bu', ruleNote: "Irregular: bu" },
  { id: 'pc3', verb: 'Dormir', subject: 'Il', conjugated: "Il a dormi", translation: "He slept", auxiliary: 'a', participle: 'dormi', ruleNote: "Regular IR: -i" },
  { id: 'pc4', verb: 'Courir', subject: 'Elle', conjugated: "Elle a couru", translation: "She ran", auxiliary: 'a', participle: 'couru', ruleNote: "Irregular: couru" },
  { id: 'pc5', verb: 'Marcher', subject: 'Nous', conjugated: "Nous avons marché", translation: "We walked", auxiliary: 'avons', participle: 'marché', ruleNote: "Uses 'avoir' + -é" },
  { id: 'pc6', verb: 'Parler', subject: 'Vous', conjugated: "Vous avez parlé", translation: "You spoke", auxiliary: 'avez', participle: 'parlé', ruleNote: "Uses 'avoir' + -é" },
  { id: 'pc7', verb: 'Lire', subject: 'Ils', conjugated: "Ils ont lu", translation: "They read", auxiliary: 'ont', participle: 'lu', ruleNote: "Irregular: lu" },
  { id: 'pc8', verb: 'Écrire', subject: 'Elles', conjugated: "Elles ont écrit", translation: "They wrote", auxiliary: 'ont', participle: 'écrit', ruleNote: "Irregular: écrit" },
  { id: 'pc9', verb: 'Chanter', subject: 'Je', conjugated: "J'ai chanté", translation: "I sang", auxiliary: 'ai', participle: 'chanté', ruleNote: "Uses 'avoir' + -é" },
  { id: 'pc10', verb: 'Danser', subject: 'Tu', conjugated: "Tu as dansé", translation: "You danced", auxiliary: 'as', participle: 'dansé', ruleNote: "Uses 'avoir' + -é" },
  { id: 'pc11', verb: 'Apprendre', subject: 'Il', conjugated: "Il a appris", translation: "He learned", auxiliary: 'a', participle: 'appris', ruleNote: "Irregular: appris" },
  { id: 'pc12', verb: 'Faire', subject: 'Elle', conjugated: "Elle a fait", translation: "She did / made", auxiliary: 'a', participle: 'fait', ruleNote: "Irregular: fait" },
  { id: 'pc13', verb: 'Aller', subject: 'Nous', conjugated: "Nous sommes allés", translation: "We went", auxiliary: 'sommes', participle: 'allés', ruleNote: "VANDERTRAMP: 'être' + agreement" },
  { id: 'pc14', verb: 'Vouloir', subject: 'Vous', conjugated: "Vous avez voulu", translation: "You wanted", auxiliary: 'avez', participle: 'voulu', ruleNote: "Irregular: voulu" },
  { id: 'pc15', verb: 'Pouvoir', subject: 'Ils', conjugated: "Ils ont pu", translation: "They could / were able", auxiliary: 'ont', participle: 'pu', ruleNote: "Irregular: pu" },
  { id: 'pc16', verb: 'Comprendre', subject: 'Elles', conjugated: "Elles ont compris", translation: "They understood", auxiliary: 'ont', participle: 'compris', ruleNote: "Irregular: compris" },
  { id: 'pc17', verb: 'Être', subject: 'Je', conjugated: "J'ai été", translation: "I was / have been", auxiliary: 'ai', participle: 'été', ruleNote: "Irregular: été (uses 'avoir')" },
  { id: 'pc18', verb: 'Avoir', subject: 'Tu', conjugated: "Tu as eu", translation: "You had", auxiliary: 'as', participle: 'eu', ruleNote: "Irregular: eu (uses 'avoir')" },
  { id: 'pc19', verb: 'Dire', subject: 'Il', conjugated: "Il a dit", translation: "He said", auxiliary: 'a', participle: 'dit', ruleNote: "Irregular: dit" },
  { id: 'pc20', verb: 'Voir', subject: 'Elle', conjugated: "Elle a vu", translation: "She saw", auxiliary: 'a', participle: 'vu', ruleNote: "Irregular: vu" },
  { id: 'pc21', verb: 'Savoir', subject: 'Nous', conjugated: "Nous avons su", translation: "We knew", auxiliary: 'avons', participle: 'su', ruleNote: "Irregular: su" },
  { id: 'pc22', verb: 'Prendre', subject: 'Vous', conjugated: "Vous avez pris", translation: "You took", auxiliary: 'avez', participle: 'pris', ruleNote: "Irregular: pris" },
  { id: 'pc23', verb: 'Venir', subject: 'Ils', conjugated: "Ils sont venus", translation: "They came", auxiliary: 'sont', participle: 'venus', ruleNote: "VANDERTRAMP: 'être' + agreement" },
  { id: 'pc24', verb: 'Trouver', subject: 'Elles', conjugated: "Elles ont trouvé", translation: "They found", auxiliary: 'ont', participle: 'trouvé', ruleNote: "Uses 'avoir' + -é" },
  { id: 'pc25', verb: 'Donner', subject: 'Je', conjugated: "J'ai donné", translation: "I gave", auxiliary: 'ai', participle: 'donné', ruleNote: "Uses 'avoir' + -é" },
  { id: 'pc26', verb: 'Falloir', subject: 'Il', conjugated: "Il a fallu", translation: "It was necessary", auxiliary: 'a', participle: 'fallu', ruleNote: "Impersonal verb: fallu" },
  { id: 'pc27', verb: 'Devoir', subject: 'Tu', conjugated: "Tu as dû", translation: "You had to", auxiliary: 'as', participle: 'dû', ruleNote: "Irregular: dû" },
  { id: 'pc28', verb: 'Croire', subject: 'Il', conjugated: "Il a cru", translation: "He believed", auxiliary: 'a', participle: 'cru', ruleNote: "Irregular: cru" },
  { id: 'pc29', verb: 'Penser', subject: 'Elle', conjugated: "Elle a pensé", translation: "She thought", auxiliary: 'a', participle: 'pensé', ruleNote: "Uses 'avoir' + -é" },
  { id: 'pc30', verb: 'Attendre', subject: 'Nous', conjugated: "Nous avons attendu", translation: "We waited", auxiliary: 'avons', participle: 'attendu', ruleNote: "Regular RE: -u" },
  { id: 'pc31', verb: 'Arriver', subject: 'Vous', conjugated: "Vous êtes arrivés", translation: "You arrived", auxiliary: 'êtes', participle: 'arrivés', ruleNote: "VANDERTRAMP: 'être' + agreement" },
  { id: 'pc32', verb: 'Partir', subject: 'Ils', conjugated: "Ils sont partis", translation: "They left", auxiliary: 'sont', participle: 'partis', ruleNote: "VANDERTRAMP: 'être' + agreement" },
  { id: 'pc33', verb: 'Sortir', subject: 'Elles', conjugated: "Elles sont sorties", translation: "They went out", auxiliary: 'sont', participle: 'sorties', ruleNote: "VANDERTRAMP: 'être' + agreement" },
  { id: 'pc34', verb: 'Entendre', subject: 'Je', conjugated: "J'ai entendu", translation: "I heard", auxiliary: 'ai', participle: 'entendu', ruleNote: "Regular RE: -u" },
  { id: 'pc35', verb: 'Regarder', subject: 'Tu', conjugated: "Tu as regardé", translation: "You looked", auxiliary: 'as', participle: 'regardé', ruleNote: "Uses 'avoir' + -é" },
  { id: 'pc36', verb: 'Répondre', subject: 'Il', conjugated: "Il a répondu", translation: "He answered", auxiliary: 'a', participle: 'répondu', ruleNote: "Regular RE: -u" },
  { id: 'pc37', verb: 'Demander', subject: 'Elle', conjugated: "Elle a demandé", translation: "She asked", auxiliary: 'a', participle: 'demandé', ruleNote: "Uses 'avoir' + -é" },
  { id: 'pc38', verb: 'Devenir', subject: 'Nous', conjugated: "Nous sommes devenus", translation: "We became", auxiliary: 'sommes', participle: 'devenus', ruleNote: "VANDERTRAMP: 'être' + agreement" },
  { id: 'pc39', verb: 'Mettre', subject: 'Vous', conjugated: "Vous avez mis", translation: "You put", auxiliary: 'avez', participle: 'mis', ruleNote: "Irregular: mis" },
  { id: 'pc40', verb: 'Connaître', subject: 'Ils', conjugated: "Ils ont connu", translation: "They knew", auxiliary: 'ont', participle: 'connu', ruleNote: "Irregular: connu" },
];

export const IMPARFAIT_DRILLS: ConjugationDrill[] = [
  { id: 'im1', verb: 'Manger', subject: 'Je', conjugated: "Je mangeais", translation: "I was eating", auxiliary: 'mange', participle: 'ais', ruleNote: "Stem: nous form -ons" },
  { id: 'im2', verb: 'Boire', subject: 'Tu', conjugated: "Tu buvais", translation: "You were drinking", auxiliary: 'buv', participle: 'ais', ruleNote: "Stem: buv-" },
  { id: 'im3', verb: 'Dormir', subject: 'Il', conjugated: "Il dormait", translation: "He was sleeping", auxiliary: 'dorm', participle: 'ait', ruleNote: "Regular -ait" },
  { id: 'im4', verb: 'Courir', subject: 'Elle', conjugated: "Elle courait", translation: "She was running", auxiliary: 'cour', participle: 'ait', ruleNote: "Stem: cour-" },
  { id: 'im5', verb: 'Marcher', subject: 'Nous', conjugated: "Nous marchions", translation: "We were walking", auxiliary: 'march', participle: 'ions', ruleNote: "Ending: -ions" },
  { id: 'im6', verb: 'Parler', subject: 'Vous', conjugated: "Vous parliez", translation: "You were speaking", auxiliary: 'parl', participle: 'iez', ruleNote: "Ending: -iez" },
  { id: 'im7', verb: 'Lire', subject: 'Ils', conjugated: "Ils lisaient", translation: "They were reading", auxiliary: 'lis', participle: 'aient', ruleNote: "Stem: lis-" },
  { id: 'im8', verb: 'Écrire', subject: 'Elles', conjugated: "Elles écrivaient", translation: "They were writing", auxiliary: 'écriv', participle: 'aient', ruleNote: "Stem: écriv-" },
  { id: 'im9', verb: 'Chanter', subject: 'Je', conjugated: "Je chantais", translation: "I was singing", auxiliary: 'chant', participle: 'ais', ruleNote: "Regular -ais" },
  { id: 'im10', verb: 'Danser', subject: 'Tu', conjugated: "Tu dansais", translation: "You were dancing", auxiliary: 'dans', participle: 'ais', ruleNote: "Regular -ais" },
  { id: 'im11', verb: 'Apprendre', subject: 'Il', conjugated: "Il apprenait", translation: "He was learning", auxiliary: 'appren', participle: 'ait', ruleNote: "Stem: appren-" },
  { id: 'im12', verb: 'Faire', subject: 'Elle', conjugated: "Elle faisait", translation: "She was doing", auxiliary: 'fais', participle: 'ait', ruleNote: "Stem: fais- (sounds like 'fes')" },
  { id: 'im13', verb: 'Aller', subject: 'Nous', conjugated: "Nous allions", translation: "We were going", auxiliary: 'all', participle: 'ions', ruleNote: "Stem: all-" },
  { id: 'im14', verb: 'Vouloir', subject: 'Vous', conjugated: "Vous vouliez", translation: "You were wanting", auxiliary: 'voul', participle: 'iez', ruleNote: "Stem: voul-" },
  { id: 'im15', verb: 'Pouvoir', subject: 'Ils', conjugated: "Ils pouvaient", translation: "They were able to", auxiliary: 'pouv', participle: 'aient', ruleNote: "Stem: pouv-" },
  { id: 'im16', verb: 'Comprendre', subject: 'Elles', conjugated: "Elles comprenaient", translation: "They were understanding", auxiliary: 'compren', participle: 'aient', ruleNote: "Stem: compren-" },
  { id: 'im17', verb: 'Être', subject: 'Je', conjugated: "J'étais", translation: "I was", auxiliary: 'ét', participle: 'ais', ruleNote: "Unique stem: ét-" },
  { id: 'im18', verb: 'Avoir', subject: 'Tu', conjugated: "Tu avais", translation: "You had", auxiliary: 'av', participle: 'ais', ruleNote: "Stem: av-" },
  { id: 'im19', verb: 'Dire', subject: 'Il', conjugated: "Il disait", translation: "He was saying", auxiliary: 'dis', participle: 'ait', ruleNote: "Stem: dis-" },
  { id: 'im20', verb: 'Voir', subject: 'Elle', conjugated: "Elle voyait", translation: "She was seeing", auxiliary: 'voy', participle: 'ait', ruleNote: "Stem: voy-" },
  { id: 'im21', verb: 'Savoir', subject: 'Nous', conjugated: "Nous savions", translation: "We knew", auxiliary: 'sav', participle: 'ions', ruleNote: "Stem: sav-" },
  { id: 'im22', verb: 'Prendre', subject: 'Vous', conjugated: "Vous preniez", translation: "You were taking", auxiliary: 'pren', participle: 'iez', ruleNote: "Stem: pren-" },
  { id: 'im23', verb: 'Venir', subject: 'Ils', conjugated: "Ils venaient", translation: "They were coming", auxiliary: 'ven', participle: 'aient', ruleNote: "Stem: ven-" },
  { id: 'im24', verb: 'Trouver', subject: 'Elles', conjugated: "Elles trouvaient", translation: "They were finding", auxiliary: 'trouv', participle: 'aient', ruleNote: "Regular -aient" },
  { id: 'im25', verb: 'Donner', subject: 'Je', conjugated: "Je donnais", translation: "I was giving", auxiliary: 'donn', participle: 'ais', ruleNote: "Regular -ais" },
  { id: 'im26', verb: 'Falloir', subject: 'Il', conjugated: "Il fallait", translation: "It was necessary", auxiliary: 'fall', participle: 'ait', ruleNote: "Only 'il' form" },
  { id: 'im27', verb: 'Devoir', subject: 'Tu', conjugated: "Tu devais", translation: "You were having to", auxiliary: 'dev', participle: 'ais', ruleNote: "Stem: dev-" },
  { id: 'im28', verb: 'Croire', subject: 'Il', conjugated: "Il croyait", translation: "He believed", auxiliary: 'croy', participle: 'ait', ruleNote: "Stem: croy-" },
  { id: 'im29', verb: 'Penser', subject: 'Elle', conjugated: "Elle pensait", translation: "She was thinking", auxiliary: 'pens', participle: 'ait', ruleNote: "Regular -ait" },
  { id: 'im30', verb: 'Attendre', subject: 'Nous', conjugated: "Nous attendions", translation: "We were waiting", auxiliary: 'attend', participle: 'ions', ruleNote: "Regular -ions" },
  { id: 'im31', verb: 'Arriver', subject: 'Vous', conjugated: "Vous arriviez", translation: "You were arriving", auxiliary: 'arriv', participle: 'iez', ruleNote: "Regular -iez" },
  { id: 'im32', verb: 'Partir', subject: 'Ils', conjugated: "Ils partaient", translation: "They were leaving", auxiliary: 'part', participle: 'aient', ruleNote: "Stem: part-" },
  { id: 'im33', verb: 'Sortir', subject: 'Elles', conjugated: "Elles sortaient", translation: "They were going out", auxiliary: 'sort', participle: 'aient', ruleNote: "Stem: sort-" },
  { id: 'im34', verb: 'Entendre', subject: 'Je', conjugated: "J'entendais", translation: "I heard", auxiliary: 'entend', participle: 'ais', ruleNote: "Regular -ais" },
  { id: 'im35', verb: 'Regarder', subject: 'Tu', conjugated: "Tu regardais", translation: "You were looking", auxiliary: 'regard', participle: 'ais', ruleNote: "Regular -ais" },
  { id: 'im36', verb: 'Répondre', subject: 'Il', conjugated: "Il répondait", translation: "He was answering", auxiliary: 'répond', participle: 'ait', ruleNote: "Regular -ait" },
  { id: 'im37', verb: 'Demander', subject: 'Elle', conjugated: "Elle demandait", translation: "She was asking", auxiliary: 'demand', participle: 'ait', ruleNote: "Regular -ait" },
  { id: 'im38', verb: 'Devenir', subject: 'Nous', conjugated: "Nous devenions", translation: "We were becoming", auxiliary: 'deven', participle: 'ions', ruleNote: "Stem: deven-" },
  { id: 'im39', verb: 'Mettre', subject: 'Vous', conjugated: "Vous mettiez", translation: "You were putting", auxiliary: 'mett', participle: 'iez', ruleNote: "Stem: mett-" },
  { id: 'im40', verb: 'Connaître', subject: 'Ils', conjugated: "Ils connaissaient", translation: "They knew", auxiliary: 'connaiss', participle: 'aient', ruleNote: "Stem: connaiss-" },
];

export const FUTUR_SIMPLE_DRILLS: ConjugationDrill[] = [
  { id: 'fs1', verb: 'Manger', subject: 'Je', conjugated: "Je mangerai", translation: "I will eat", auxiliary: 'manger', participle: 'ai', ruleNote: "Inf. + -ai" },
  { id: 'fs2', verb: 'Boire', subject: 'Tu', conjugated: "Tu boiras", translation: "You will drink", auxiliary: 'boir', participle: 'as', ruleNote: "Inf. + -as" },
  { id: 'fs3', verb: 'Dormir', subject: 'Il', conjugated: "Il dormira", translation: "He will sleep", auxiliary: 'dormir', participle: 'a', ruleNote: "Inf. + -a" },
  { id: 'fs4', verb: 'Courir', subject: 'Elle', conjugated: "Elle courra", translation: "She will run", auxiliary: 'courr', participle: 'a', ruleNote: "Irregular: courr-" },
  { id: 'fs5', verb: 'Marcher', subject: 'Nous', conjugated: "Nous marcherons", translation: "We will walk", auxiliary: 'marcher', participle: 'ons', ruleNote: "Inf. + -ons" },
  { id: 'fs6', verb: 'Parler', subject: 'Vous', conjugated: "Vous parlerez", translation: "You will speak", auxiliary: 'parler', participle: 'ez', ruleNote: "Inf. + -ez" },
  { id: 'fs7', verb: 'Lire', subject: 'Ils', conjugated: "Ils liront", translation: "They will read", auxiliary: 'lir', participle: 'ont', ruleNote: "Inf. + -ont" },
  { id: 'fs8', verb: 'Écrire', subject: 'Elles', conjugated: "Elles écriront", translation: "They will write", auxiliary: 'écrir', participle: 'ont', ruleNote: "Inf. + -ont" },
  { id: 'fs9', verb: 'Chanter', subject: 'Je', conjugated: "Je chanterai", translation: "I will sing", auxiliary: 'chanter', participle: 'ai', ruleNote: "Regular -ai" },
  { id: 'fs10', verb: 'Danser', subject: 'Tu', conjugated: "Tu danseras", translation: "You will dance", auxiliary: 'danser', participle: 'as', ruleNote: "Regular -as" },
  { id: 'fs11', verb: 'Apprendre', subject: 'Il', conjugated: "Il apprendra", translation: "He will learn", auxiliary: 'apprendr', participle: 'a', ruleNote: "Inf. -e + -a" },
  { id: 'fs12', verb: 'Faire', subject: 'Elle', conjugated: "Elle fera", translation: "She will do", auxiliary: 'fer', participle: 'a', ruleNote: "Irregular stem: fer-" },
  { id: 'fs13', verb: 'Aller', subject: 'Nous', conjugated: "Nous irons", translation: "We will go", auxiliary: 'ir', participle: 'ons', ruleNote: "Irregular stem: ir-" },
  { id: 'fs14', verb: 'Vouloir', subject: 'Vous', conjugated: "Vous voudrez", translation: "You will want", auxiliary: 'voudr', participle: 'ez', ruleNote: "Irregular stem: voudr-" },
  { id: 'fs15', verb: 'Pouvoir', subject: 'Ils', conjugated: "Ils pourront", translation: "They will be able to", auxiliary: 'pourr', participle: 'ont', ruleNote: "Irregular stem: pourr-" },
  { id: 'fs16', verb: 'Comprendre', subject: 'Elles', conjugated: "Elles comprendront", translation: "They will understand", auxiliary: 'comprendr', participle: 'ont', ruleNote: "Inf. -e + -ont" },
  { id: 'fs17', verb: 'Être', subject: 'Je', conjugated: "Je serai", translation: "I will be", auxiliary: 'ser', participle: 'ai', ruleNote: "Irregular stem: ser-" },
  { id: 'fs18', verb: 'Avoir', subject: 'Tu', conjugated: "Tu auras", translation: "You will have", auxiliary: 'aur', participle: 'as', ruleNote: "Irregular stem: aur-" },
  { id: 'fs19', verb: 'Dire', subject: 'Il', conjugated: "Il dira", translation: "He will say", auxiliary: 'dir', participle: 'a', ruleNote: "Inf. -e + -a" },
  { id: 'fs20', verb: 'Voir', subject: 'Elle', conjugated: "Elle verra", translation: "She will see", auxiliary: 'verr', participle: 'a', ruleNote: "Irregular stem: verr-" },
  { id: 'fs21', verb: 'Savoir', subject: 'Nous', conjugated: "Nous saurons", translation: "We will know", auxiliary: 'saur', participle: 'ons', ruleNote: "Irregular stem: saur-" },
  { id: 'fs22', verb: 'Prendre', subject: 'Vous', conjugated: "Vous prendrez", translation: "You will take", auxiliary: 'prendr', participle: 'ez', ruleNote: "Inf. -e + -ez" },
  { id: 'fs23', verb: 'Venir', subject: 'Ils', conjugated: "Ils viendront", translation: "They will come", auxiliary: 'viendr', participle: 'ont', ruleNote: "Irregular stem: viendr-" },
  { id: 'fs24', verb: 'Trouver', subject: 'Elles', conjugated: "Elles trouveront", translation: "They will find", auxiliary: 'trouver', participle: 'ont', ruleNote: "Regular -ont" },
  { id: 'fs25', verb: 'Donner', subject: 'Je', conjugated: "Je donnerai", translation: "I will give", auxiliary: 'donner', participle: 'ai', ruleNote: "Regular -ai" },
  { id: 'fs26', verb: 'Falloir', subject: 'Il', conjugated: "Il faudra", translation: "It will be necessary", auxiliary: 'faudr', participle: 'a', ruleNote: "Irregular stem: faudr-" },
  { id: 'fs27', verb: 'Devoir', subject: 'Tu', conjugated: "Tu devras", translation: "You will have to", auxiliary: 'devr', participle: 'as', ruleNote: "Irregular stem: devr-" },
  { id: 'fs28', verb: 'Croire', subject: 'Il', conjugated: "Il croira", translation: "He will believe", auxiliary: 'croir', participle: 'a', ruleNote: "Inf. -e + -a" },
  { id: 'fs29', verb: 'Penser', subject: 'Elle', conjugated: "Elle pensera", translation: "She will think", auxiliary: 'penser', participle: 'a', ruleNote: "Regular -a" },
  { id: 'fs30', verb: 'Attendre', subject: 'Nous', conjugated: "Nous attendrons", translation: "We will wait", auxiliary: 'attendr', participle: 'ons', ruleNote: "Inf. -e + -ons" },
  { id: 'fs31', verb: 'Arriver', subject: 'Vous', conjugated: "Vous arriverez", translation: "You will arrive", auxiliary: 'arriver', participle: 'ez', ruleNote: "Regular -ez" },
  { id: 'fs32', verb: 'Partir', subject: 'Ils', conjugated: "Ils partiront", translation: "They will leave", auxiliary: 'partir', participle: 'ont', ruleNote: "Regular -ont" },
  { id: 'fs33', verb: 'Sortir', subject: 'Elles', conjugated: "Elles sortiront", translation: "They will go out", auxiliary: 'sortir', participle: 'ont', ruleNote: "Regular -ont" },
  { id: 'fs34', verb: 'Entendre', subject: 'Je', conjugated: "J'entendrai", translation: "I will hear", auxiliary: 'entender', participle: 'ai', ruleNote: "Inf. -e + -ai" },
  { id: 'fs35', verb: 'Regarder', subject: 'Tu', conjugated: "Tu regarderas", translation: "You will look", auxiliary: 'regarder', participle: 'as', ruleNote: "Regular -as" },
  { id: 'fs36', verb: 'Répondre', subject: 'Il', conjugated: "Il répondra", translation: "He will answer", auxiliary: 'répondr', participle: 'a', ruleNote: "Inf. -e + -a" },
  { id: 'fs37', verb: 'Demander', subject: 'Elle', conjugated: "Elle demandera", translation: "She will ask", auxiliary: 'demander', participle: 'a', ruleNote: "Regular -a" },
  { id: 'fs38', verb: 'Devenir', subject: 'Nous', conjugated: "Nous deviendrons", translation: "We will become", auxiliary: 'deviendr', participle: 'ons', ruleNote: "Irregular stem: viendr-" },
  { id: 'fs39', verb: 'Mettre', subject: 'Vous', conjugated: "Vous mettrez", translation: "You will put", auxiliary: 'mettr', participle: 'ez', ruleNote: "Inf. -e + -ez" },
  { id: 'fs40', verb: 'Connaître', subject: 'Ils', conjugated: "Ils connaîtront", translation: "They will know", auxiliary: 'connaîtr', participle: 'ont', ruleNote: "Inf. -e + -ont" },
];

export const CONDITIONNEL_PRESENT_DRILLS: ConjugationDrill[] = [
  { id: 'cp1', verb: 'Manger', subject: 'Je', conjugated: "Je mangerais", translation: "I would eat", auxiliary: 'manger', participle: 'ais', ruleNote: "Futur stem + Imparfait end" },
  { id: 'cp2', verb: 'Boire', subject: 'Tu', conjugated: "Tu boirais", translation: "You would drink", auxiliary: 'boir', participle: 'ais', ruleNote: "Stem: boir-" },
  { id: 'cp3', verb: 'Dormir', subject: 'Il', conjugated: "Il dormirait", translation: "He would sleep", auxiliary: 'dormir', participle: 'ait', ruleNote: "Stem: dormir-" },
  { id: 'cp4', verb: 'Courir', subject: 'Elle', conjugated: "Elle courrait", translation: "She would run", auxiliary: 'courr', participle: 'ait', ruleNote: "Stem: courr-" },
  { id: 'cp5', verb: 'Marcher', subject: 'Nous', conjugated: "Nous marcherions", translation: "We would walk", auxiliary: 'marcher', participle: 'ions', ruleNote: "Ending -ions" },
  { id: 'cp6', verb: 'Parler', subject: 'Vous', conjugated: "Vous parleriez", translation: "You would speak", auxiliary: 'parler', participle: 'iez', ruleNote: "Ending -iez" },
  { id: 'cp7', verb: 'Lire', subject: 'Ils', conjugated: "Ils liraient", translation: "They would read", auxiliary: 'lir', participle: 'aient', ruleNote: "Ending -aient" },
  { id: 'cp8', verb: 'Écrire', subject: 'Elles', conjugated: "Elles écriraient", translation: "They would write", auxiliary: 'écrir', participle: 'aient', ruleNote: "Ending -aient" },
  { id: 'cp9', verb: 'Chanter', subject: 'Je', conjugated: "Je chanterais", translation: "I would sing", auxiliary: 'chanter', participle: 'ais', ruleNote: "Regular -ais" },
  { id: 'cp10', verb: 'Danser', subject: 'Tu', conjugated: "Tu danserais", translation: "You would dance", auxiliary: 'danser', participle: 'ais', ruleNote: "Regular -ais" },
  { id: 'cp11', verb: 'Apprendre', subject: 'Il', conjugated: "Il apprendrait", translation: "He would learn", auxiliary: 'apprendr', participle: 'ait', ruleNote: "Stem: apprendr-" },
  { id: 'cp12', verb: 'Faire', subject: 'Elle', conjugated: "Elle ferait", translation: "She would do", auxiliary: 'fer', participle: 'ait', ruleNote: "Stem: fer-" },
  { id: 'cp13', verb: 'Aller', subject: 'Nous', conjugated: "Nous irions", translation: "We would go", auxiliary: 'ir', participle: 'ions', ruleNote: "Stem: ir-" },
  { id: 'cp14', verb: 'Vouloir', subject: 'Vous', conjugated: "Vous voudriez", translation: "You would want", auxiliary: 'voudr', participle: 'iez', ruleNote: "Stem: voudr-" },
  { id: 'cp15', verb: 'Pouvoir', subject: 'Ils', conjugated: "Ils pourraient", translation: "They would be able to", auxiliary: 'pourr', participle: 'aient', ruleNote: "Stem: pourr-" },
  { id: 'cp16', verb: 'Comprendre', subject: 'Elles', conjugated: "Elles comprendraient", translation: "They would understand", auxiliary: 'comprendr', participle: 'aient', ruleNote: "Stem: comprendr-" },
  { id: 'cp17', verb: 'Être', subject: 'Je', conjugated: "Je serais", translation: "I would be", auxiliary: 'ser', participle: 'ais', ruleNote: "Stem: ser-" },
  { id: 'cp18', verb: 'Avoir', subject: 'Tu', conjugated: "Tu aurais", translation: "You would have", auxiliary: 'aur', participle: 'ais', ruleNote: "Stem: aur-" },
  { id: 'cp19', verb: 'Dire', subject: 'Il', conjugated: "Il dirait", translation: "He would say", auxiliary: 'dir', participle: 'ait', ruleNote: "Stem: dir-" },
  { id: 'cp20', verb: 'Voir', subject: 'Elle', conjugated: "Elle verrait", translation: "She would see", auxiliary: 'verr', participle: 'ait', ruleNote: "Stem: verr-" },
  { id: 'cp21', verb: 'Savoir', subject: 'Nous', conjugated: "Nous saurions", translation: "We would know", auxiliary: 'saur', participle: 'ions', ruleNote: "Stem: saur-" },
  { id: 'cp22', verb: 'Prendre', subject: 'Vous', conjugated: "Vous prendriez", translation: "You would take", auxiliary: 'prendr', participle: 'iez', ruleNote: "Stem: prendr-" },
  { id: 'cp23', verb: 'Venir', subject: 'Ils', conjugated: "Ils viendraient", translation: "They would come", auxiliary: 'viendr', participle: 'aient', ruleNote: "Stem: viendr-" },
  { id: 'cp24', verb: 'Trouver', subject: 'Elles', conjugated: "Elles trouveraient", translation: "They would find", auxiliary: 'trouver', participle: 'aient', ruleNote: "Regular -aient" },
  { id: 'cp25', verb: 'Donner', subject: 'Je', conjugated: "Je donnerais", translation: "I would give", auxiliary: 'donner', participle: 'ais', ruleNote: "Regular -ais" },
  { id: 'cp26', verb: 'Falloir', subject: 'Il', conjugated: "Il faudrait", translation: "It would be necessary", auxiliary: 'faudr', participle: 'ait', ruleNote: "Stem: faudr-" },
  { id: 'cp27', verb: 'Devoir', subject: 'Tu', conjugated: "Tu devrais", translation: "You would have to", auxiliary: 'devr', participle: 'ais', ruleNote: "Stem: devr-" },
  { id: 'cp28', verb: 'Croire', subject: 'Il', conjugated: "Il croira", translation: "He would believe", auxiliary: 'croir', participle: 'ait', ruleNote: "Stem: croir-" },
  { id: 'cp29', verb: 'Penser', subject: 'Elle', conjugated: "Elle penserait", translation: "She would think", auxiliary: 'penser', participle: 'ait', ruleNote: "Regular -ait" },
  { id: 'cp30', verb: 'Attendre', subject: 'Nous', conjugated: "Nous attendrions", translation: "We would wait", auxiliary: 'attendr', participle: 'ions', ruleNote: "Stem: attendr-" },
  { id: 'cp31', verb: 'Arriver', subject: 'Vous', conjugated: "Vous arriveriez", translation: "You would arrive", auxiliary: 'arriver', participle: 'iez', ruleNote: "Regular -iez" },
  { id: 'cp32', verb: 'Partir', subject: 'Ils', conjugated: "Ils partiraient", translation: "They would leave", auxiliary: 'partir', participle: 'aient', ruleNote: "Regular -aient" },
  { id: 'cp33', verb: 'Sortir', subject: 'Elles', conjugated: "Elles sortiront", translation: "They would go out", auxiliary: 'sortir', participle: 'aient', ruleNote: "Regular -aient" },
  { id: 'cp34', verb: 'Entendre', subject: 'Je', conjugated: "J'entendrais", translation: "I would hear", auxiliary: 'entender', participle: 'ais', ruleNote: "Stem: entender-" },
  { id: 'cp35', verb: 'Regarder', subject: 'Tu', conjugated: "Tu regarderais", translation: "You would look", auxiliary: 'regarder', participle: 'ais', ruleNote: "Regular -ais" },
  { id: 'cp36', verb: 'Répondre', subject: 'Il', conjugated: "Il répondrait", translation: "He would answer", auxiliary: 'répondr', participle: 'ait', ruleNote: "Stem: répondr-" },
  { id: 'cp37', verb: 'Demander', subject: 'Elle', conjugated: "Elle demanderait", translation: "She would ask", auxiliary: 'demander', participle: 'ait', ruleNote: "Regular -ait" },
  { id: 'cp38', verb: 'Devenir', subject: 'Nous', conjugated: "Nous deviendrions", translation: "We would become", auxiliary: 'deviendr', participle: 'ions', ruleNote: "Irregular stem: viendr-" },
  { id: 'cp39', verb: 'Mettre', subject: 'Vous', conjugated: "Vous mettriez", translation: "You would put", auxiliary: 'mettr', participle: 'iez', ruleNote: "Stem: mettr-" },
  { id: 'cp40', verb: 'Connaître', subject: 'Ils', conjugated: "Ils connaîtraient", translation: "They would know", auxiliary: 'connaîtr', participle: 'aient', ruleNote: "Stem: connaîtr-" },
];

export const FRENCH_VOCABULARY: Word[] = [
  // Greetings & Basics
  { id: 'v1', french: 'Bonjour', english: 'Hello', category: 'Greetings', exampleFrench: "Bonjour, comment ça va ?", exampleEnglish: "Hello, how are you?" },
  { id: 'v2', french: 'Merci', english: 'Thank you', category: 'Greetings', exampleFrench: "Merci pour votre aide.", exampleEnglish: "Thank you for your help." },
  
  // Introductions
  { id: 'intro1', french: 'Se présenter', english: 'To introduce oneself', category: 'Introductions', exampleFrench: "Je voudrais me présenter.", exampleEnglish: "I would like to introduce myself." },
  { id: 'intro2', french: 'Le prénom', english: 'First name', category: 'Introductions', exampleFrench: "Quel est votre prénom ?", exampleEnglish: "What is your first name?" },
  { id: 'intro3', french: 'Enchanté', english: 'Pleased to meet you', category: 'Introductions', exampleFrench: "Enchanté de faire votre connaissance.", exampleEnglish: "Pleased to meet you." },
  { id: 'intro4', french: 'L\'âge', english: 'Age', category: 'Introductions', exampleFrench: "Quel âge as-tu ?", exampleEnglish: "How old are you?" },
  { id: 'intro5', french: 'La nationalité', english: 'Nationality', category: 'Introductions', exampleFrench: "Il est de nationalité française.", exampleEnglish: "He is of French nationality." },
  { id: 'intro6', french: 'D\'où venez-vous ?', english: 'Where are you from?', category: 'Introductions', exampleFrench: "D'où venez-vous exactement ?", exampleEnglish: "Where are you from exactly?" },
  { id: 'intro7', french: 'Célibataire', english: 'Single', category: 'Introductions', exampleFrench: "Il est célibataire pour le moment.", exampleEnglish: "He is single at the moment." },
  { id: 'intro8', french: 'Habiter', english: 'To live', category: 'Introductions', exampleFrench: "Où habitez-vous ?", exampleEnglish: "Where do you live?" },

  // Hobbies
  { id: 'hob1', french: 'Le temps libre', english: 'Spare time', category: 'Hobbies', exampleFrench: "Qu'aimez-vous faire de votre temps libre ?", exampleEnglish: "What do you like to do in your spare time?" },
  { id: 'hob2', french: 'Cuisiner', english: 'Cooking', category: 'Hobbies', exampleFrench: "Ma passion est de cuisiner.", exampleEnglish: "My passion is cooking." },
  { id: 'hob3', french: 'Le sport', english: 'Sport', category: 'Hobbies', exampleFrench: "Je pratique beaucoup de sport.", exampleEnglish: "I do a lot of sport." },
  { id: 'hob4', french: 'La lecture', english: 'Reading', category: 'Hobbies', exampleFrench: "La lecture est relaxante.", exampleEnglish: "Reading is relaxing." },
  { id: 'hob5', french: 'Voyager', english: 'Travelling', category: 'Hobbies', exampleFrench: "Elle adore voyager à travers le monde.", exampleEnglish: "She loves travelling around the world." },
  { id: 'hob6', french: 'Le jardinage', english: 'Gardening', category: 'Hobbies', exampleFrench: "Le jardinage demande de la patience.", exampleEnglish: "Gardening requires patience." },
  { id: 'hob7', french: 'Peindre', english: 'Painting', category: 'Hobbies', exampleFrench: "Il a commencé à peindre l'année dernière.", exampleEnglish: "He started painting last year." },
  { id: 'hob8', french: 'La photographie', english: 'Photography', category: 'Hobbies', exampleFrench: "La photographie est un bel art.", exampleEnglish: "Photography is a beautiful art." },

  // Memories
  { id: 'mem1', french: 'Un souvenir', english: 'A memory', category: 'Memories', exampleFrench: "C'est un beau souvenir d'enfance.", exampleEnglish: "It's a beautiful childhood memory." },
  { id: 'mem2', french: 'Se rappeler', english: 'To remember', category: 'Memories', exampleFrench: "Je me rappelle très bien de ce jour.", exampleEnglish: "I remember that day very well." },
  { id: 'mem3', french: 'Oublier', english: 'To forget', category: 'Memories', exampleFrench: "N'oublie pas d'acheter le lait.", exampleEnglish: "Don't forget to buy the milk." },
  { id: 'mem4', french: 'Nostalgique', english: 'Nostalgic', category: 'Memories', exampleFrench: "Elle se sent un peu nostalgique aujourd'hui.", exampleEnglish: "She feels a bit nostalgic today." },
  { id: 'mem5', french: 'L\'enfance', english: 'Childhood', category: 'Memories', exampleFrench: "Mon enfance était très heureuse.", exampleEnglish: "My childhood was very happy." },
  { id: 'mem6', french: 'Raconter', english: 'To relate / tell', category: 'Memories', exampleFrench: "Raconte-moi une histoire.", exampleEnglish: "Tell me a story." },
  { id: 'mem7', french: 'Le passé', english: 'The past', category: 'Memories', exampleFrench: "On ne peut pas changer le passé.", exampleEnglish: "One cannot change the past." },
  { id: 'mem8', french: 'Émouvant', english: 'Moving / Touching', category: 'Memories', exampleFrench: "C'est un film très émouvant.", exampleEnglish: "It's a very moving film." },

  // Senses
  { id: 'sen1', french: 'La vue', english: 'Sight', category: 'Senses', exampleFrench: "La vue est magnifique d'ici.", exampleEnglish: "The sight is magnificent from here." },
  { id: 'sen2', french: 'L\'odorat', english: 'Smell', category: 'Senses', exampleFrench: "Les chiens ont un bon odorat.", exampleEnglish: "Dogs have a good sense of smell." },
  { id: 'sen3', french: 'Le goût', english: 'Taste', category: 'Senses', exampleFrench: "Ce plat a un goût délicieux.", exampleEnglish: "This dish has a delicious taste." },
  { id: 'sen4', french: 'L\'ouïe', english: 'Hearing', category: 'Senses', exampleFrench: "Elle a l'ouïe très fine.", exampleEnglish: "She has very fine hearing." },
  { id: 'sen5', french: 'Le toucher', english: 'Touch', category: 'Senses', exampleFrench: "C'est doux au toucher.", exampleEnglish: "It's soft to the touch." },
  { id: 'sen6', french: 'Sentir', english: 'To smell / feel', category: 'Senses', exampleFrench: "Je sens le parfum des fleurs.", exampleEnglish: "I smell the perfume of the flowers." },
  { id: 'sen7', french: 'Regarder', english: 'To look at', category: 'Senses', exampleFrench: "Regarde cet oiseau !", exampleEnglish: "Look at that bird!" },
  { id: 'sen8', french: 'Écouter', english: 'To listen', category: 'Senses', exampleFrench: "J'aime écouter de la musique.", exampleEnglish: "I like listening to music." },

  // Accommodation
  { id: 'acc1', french: 'Un appartement', english: 'A flat', category: 'Accommodation', exampleFrench: "J'habite dans un petit appartement.", exampleEnglish: "I live in a small flat." },
  { id: 'acc2', french: 'Le loyer', english: 'Rent', category: 'Accommodation', exampleFrench: "Le loyer est cher dans le centre.", exampleEnglish: "Rent is expensive in the centre." },
  { id: 'acc3', french: 'Un colocataire', english: 'A flatmate', category: 'Accommodation', exampleFrench: "Mon colocataire est très ordonné.", exampleEnglish: "My flatmate is very tidy." },
  { id: 'acc4', french: 'Meublé', english: 'Furnished', category: 'Accommodation', exampleFrench: "L'appartement est loué meublé.", exampleEnglish: "The flat is let furnished." },
  { id: 'acc5', french: 'Le rez-de-chaussée', english: 'Ground floor', category: 'Accommodation', exampleFrench: "Elle habite au rez-de-chaussée.", exampleEnglish: "She lives on the ground floor." },
  { id: 'acc6', french: 'Déménager', english: 'To move house', category: 'Accommodation', exampleFrench: "Nous allons déménager le mois prochain.", exampleEnglish: "We are going to move house next month." },
  { id: 'acc7', french: 'Une chambre', english: 'A bedroom', category: 'Accommodation', exampleFrench: "La chambre est spacieuse.", exampleEnglish: "The bedroom is spacious." },
  { id: 'acc8', french: 'Le quartier', english: 'Neighbourhood', category: 'Accommodation', exampleFrench: "C'est un quartier calme.", exampleEnglish: "It's a quiet neighbourhood." },

  // Appearance & Personality
  { id: 'per1', french: 'Mince', english: 'Thin', category: 'Appearance & Personality', exampleFrench: "Elle est devenue très mince.", exampleEnglish: "She has become very thin." },
  { id: 'per2', french: 'Sympa', english: 'Nice / Friendly', category: 'Appearance & Personality', exampleFrench: "Il est vraiment très sympa.", exampleEnglish: "He is really very friendly." },
  { id: 'per3', french: 'Bavard', english: 'Chatty', category: 'Appearance & Personality', exampleFrench: "Mon petit frère est très bavard.", exampleEnglish: "My little brother is very chatty." },
  { id: 'per4', french: 'Honnête', english: 'Honest', category: 'Appearance & Personality', exampleFrench: "Il faut être honnête avec soi-même.", exampleEnglish: "You must be honest with yourself." },
  { id: 'per5', french: 'Têtu', english: 'Stubborn', category: 'Appearance & Personality', exampleFrench: "Elle est un peu têtue parfois.", exampleEnglish: "She is a bit stubborn sometimes." },
  { id: 'per6', french: 'Généreux', english: 'Generous', category: 'Appearance & Personality', exampleFrench: "C'est un homme très généreux.", exampleEnglish: "He is a very generous man." },
  { id: 'per7', french: 'Calme', english: 'Quiet / Calm', category: 'Appearance & Personality', exampleFrench: "C'est une personne très calme.", exampleEnglish: "She is a very quiet person." },
  { id: 'per8', french: 'Grand', english: 'Tall', category: 'Appearance & Personality', exampleFrench: "Il est très grand pour son âge.", exampleEnglish: "He is very tall for his age." },

  // Technology
  { id: 'tec1', french: 'Un ordinateur', english: 'A computer', category: 'Technology', exampleFrench: "J'utilise mon ordinateur pour travailler.", exampleEnglish: "I use my computer for work." },
  { id: 'tec2', french: 'Le logiciel', english: 'Software', category: 'Technology', exampleFrench: "Ce logiciel est très utile.", exampleEnglish: "This software is very useful." },
  { id: 'tec3', french: 'Télécharger', english: 'To download', category: 'Technology', exampleFrench: "Tu peux télécharger l'application ici.", exampleEnglish: "You can download the application here." },
  { id: 'tec4', french: 'Un écran', english: 'A screen', category: 'Technology', exampleFrench: "L'écran est trop brillant.", exampleEnglish: "The screen is too bright." },
  { id: 'tec5', french: 'Le réseau', english: 'Network', category: 'Technology', exampleFrench: "Le réseau est lent aujourd'hui.", exampleEnglish: "The network is slow today." },
  { id: 'tec6', french: 'Un smartphone', english: 'A smartphone', category: 'Technology', exampleFrench: "Mon smartphone est déchargé.", exampleEnglish: "My smartphone is out of battery." },
  { id: 'tec7', french: 'La puce', english: 'The chip', category: 'Technology', exampleFrench: "La puce électronique est minuscule.", exampleEnglish: "The electronic chip is tiny." },
  { id: 'tec8', french: 'Connecté', english: 'Connected', category: 'Technology', exampleFrench: "Tous les appareils sont connectés.", exampleEnglish: "All the devices are connected." },

  // Food (Expanded)
  { id: 'food1', french: 'Le déjeuner', english: 'Lunch', category: 'Food', exampleFrench: "Prenons le déjeuner ensemble.", exampleEnglish: "Let's have lunch together." },
  { id: 'food2', french: 'Le dîner', english: 'Dinner', category: 'Food', exampleFrench: "Qu'est-ce qu'on mange pour le dîner ?", exampleEnglish: "What are we having for dinner?" },
  { id: 'food3', french: 'Une épice', english: 'A spice', category: 'Food', exampleFrench: "Cette épice est très forte.", exampleEnglish: "This spice is very strong." },
  { id: 'food4', french: 'Savoureux', english: 'Tasty', category: 'Food', exampleFrench: "Ce gâteau est vraiment savoureux.", exampleEnglish: "This cake is really tasty." },
  { id: 'food5', french: 'Le menu', english: 'The menu', category: 'Food', exampleFrench: "Puis-je voir le menu, s'il vous plaît ?", exampleEnglish: "May I see the menu, please?" },
  { id: 'food6', french: 'Végétarien', english: 'Vegetarian', category: 'Food', exampleFrench: "Avez-vous des plats végétariens ?", exampleEnglish: "Do you have any vegetarian dishes?" },
  { id: 'food7', french: 'Commander', english: 'To order', category: 'Food', exampleFrench: "On va commander une pizza.", exampleEnglish: "We're going to order a pizza." },
  { id: 'food8', french: 'Le goût', english: 'Flavour / Taste', category: 'Food', exampleFrench: "J'aime le goût de la vanille.", exampleEnglish: "I like the flavour of vanilla." },

  // Health, Body & Medicines
  { id: 'hea1', french: 'La santé', english: 'Health', category: 'Health & Body', exampleFrench: "La santé est le plus important.", exampleEnglish: "Health is the most important thing." },
  { id: 'hea2', french: 'Le corps', english: 'The body', category: 'Health & Body', exampleFrench: "Il faut prendre soin de son corps.", exampleEnglish: "One must take care of one's body." },
  { id: 'hea3', french: 'Un médicament', english: 'A medicine', category: 'Health & Body', exampleFrench: "Prenez ce médicament après le repas.", exampleEnglish: "Take this medicine after the meal." },
  { id: 'hea4', french: 'Le médecin', english: 'The doctor', category: 'Health & Body', exampleFrench: "Le médecin arrive bientôt.", exampleEnglish: "The doctor is coming soon." },
  { id: 'hea5', french: 'Une ordonnance', english: 'A prescription', category: 'Health & Body', exampleFrench: "J'ai besoin d'une ordonnance pour cela.", exampleEnglish: "I need a prescription for that." },
  { id: 'hea6', french: 'Malade', english: 'Ill', category: 'Health & Body', exampleFrench: "Elle est absente parce qu'elle est malade.", exampleEnglish: "She is absent because she is ill." },
  { id: 'hea7', french: 'La pharmacie', english: 'The chemist / pharmacy', category: 'Health & Body', exampleFrench: "Où est la pharmacie la plus proche ?", exampleEnglish: "Where is the nearest chemist?" },
  { id: 'hea8', french: 'Guérir', english: 'To heal / recover', category: 'Health & Body', exampleFrench: "Il va bientôt guérir.", exampleEnglish: "He will soon recover." },

  // Animals
  { id: 'v3', french: 'Chat', english: 'Cat', category: 'Animals', exampleFrench: "Le chat dort sur le canapé.", exampleEnglish: "The cat is sleeping on the sofa." },
  { id: 'v4', french: 'Chien', english: 'Dog', category: 'Animals', exampleFrench: "Mon chien aime courir au parc.", exampleEnglish: "My dog loves running in the park." },
  
  // Colours
  { id: 'v7', french: 'Rouge', english: 'Red', category: 'Colours', exampleFrench: "Elle porte une robe rouge.", exampleEnglish: "She is wearing a red dress." },
  { id: 'v8', french: 'Bleu', english: 'Blue', category: 'Colours', exampleFrench: "Le ciel est très bleu aujourd'hui.", exampleEnglish: "The sky is very blue today." },
  
  // Nature
  { id: 'v12', french: 'Soleil', english: 'Sun', category: 'Nature', exampleFrench: "Le soleil brille fort.", exampleEnglish: "The sun is shining brightly." },
  { id: 'v13', french: 'Lune', english: 'Moon', category: 'Nature', exampleFrench: "La lune est pleine ce soir.", exampleEnglish: "The moon is full tonight." },
  { id: 'v14', french: 'Eau', english: 'Water', category: 'Nature', exampleFrench: "Je voudrais un verre d'eau.", exampleEnglish: "I would like a glass of water." },
  
  // Adjectives
  { id: 'v16', french: 'Heureux', english: 'Happy', category: 'Adjectives', exampleFrench: "Je suis heureux de te voir.", exampleEnglish: "I am happy to see you." },

  // Sustainability & Environment (Legacy)
  { id: 'v25', french: 'Durable', english: 'Sustainable', category: 'Sustainability', exampleFrench: "C'est un mode de vie durable.", exampleEnglish: "It's a sustainable lifestyle." },
  { id: 'v28', french: 'L\'environnement', english: 'The environment', category: 'Sustainability', exampleFrench: "Protégeons l'environnement ensemble.", exampleEnglish: "Let's protect the environment together." },
];

export const FRENCH_VERBS: Word[] = [
  { id: 'vb1', french: 'Manger', english: 'To eat', category: 'Action', exampleFrench: "Nous aimons manger ensemble.", exampleEnglish: "We like to eat together." },
  { id: 'vb2', french: 'Boire', english: 'To drink', category: 'Action', exampleFrench: "Il faut boire beaucoup d'eau.", exampleEnglish: "It's necessary to drink a lot of water." },
  { id: 'vb3', french: 'Dormir', english: 'To sleep', category: 'Action', exampleFrench: "Le bébé va bientôt dormir.", exampleEnglish: "The baby will sleep soon." },
  { id: 'vb4', french: 'Courir', english: 'To run', category: 'Action', exampleFrench: "Je cours tous les matins.", exampleEnglish: "I run every morning." },
  { id: 'vb5', french: 'Marcher', english: 'To walk', category: 'Movement', exampleFrench: "Nous marchons dans la forêt.", exampleEnglish: "We are walking in the forest." },
  { id: 'vb6', french: 'Parler', english: 'To speak', category: 'Communication', exampleFrench: "Elle parle trois langues.", exampleEnglish: "She speaks three languages." },
  { id: 'vb7', french: 'Lire', english: 'To read', category: 'Cognition', exampleFrench: "J'aime lire avant de dormir.", exampleEnglish: "I like to read before sleeping." },
  { id: 'vb8', french: 'Écrire', english: 'To write', category: 'Cognition', exampleFrench: "Il écrit une lettre à son ami.", exampleEnglish: "He is writing a letter to his friend." },
  { id: 'vb9', french: 'Chanter', english: 'To sing', category: 'Arts', exampleFrench: "Ils chantent une belle chanson.", exampleEnglish: "They are singing a beautiful song." },
  { id: 'vb10', french: 'Danser', english: 'To dance', category: 'Arts', exampleFrench: "Voulez-vous danser avec moi ?", exampleEnglish: "Do you want to dance with me?" },
  { id: 'vb11', french: 'Apprendre', english: 'To learn', category: 'Education', exampleFrench: "J'apprends le français avec cette app.", exampleEnglish: "I am learning French with this app." },
  { id: 'vb12', french: 'Faire', english: 'To do / make', category: 'Action', exampleFrench: "Qu'est-ce que tu vas faire ?", exampleEnglish: "What are you going to do?" },
  { id: 'vb13', french: 'Aller', english: 'To go', category: 'Movement', exampleFrench: "Je vais au supermarché.", exampleEnglish: "I am going to the supermarket." },
  { id: 'vb14', french: 'Vouloir', english: 'To want', category: 'Mental', exampleFrench: "Je veux un café, s'il vous plaît.", exampleEnglish: "I want a coffee, please." },
  { id: 'vb15', french: 'Pouvoir', english: 'To be able to', category: 'Mental', exampleFrench: "Est-ce que je peux t'aider ?", exampleEnglish: "Can I help you?" },
  { id: 'vb16', french: 'Comprendre', english: 'To understand', category: 'Cognition', exampleFrench: "Je ne comprends pas cette phrase.", exampleEnglish: "I don't understand this sentence." },
  { id: 'vb17', french: 'Être', english: 'To be', category: 'State', exampleFrench: "Je veux être heureux.", exampleEnglish: "I want to be happy." },
  { id: 'vb18', french: 'Avoir', english: 'To have', category: 'Possession', exampleFrench: "J'ai un petit chat noir.", exampleEnglish: "I have a small black cat." },
  { id: 'vb19', french: 'Dire', english: 'To say', category: 'Communication', exampleFrench: "Qu'est-ce qu'il a dit ?", exampleEnglish: "What did he say?" },
  { id: 'vb20', french: 'Voir', english: 'To see', category: 'Senses', exampleFrench: "Je vois la tour Eiffel d'ici.", exampleEnglish: "I see the Eiffel Tower from here." },
  { id: 'vb21', french: 'Savoir', english: 'To know', category: 'Cognition', exampleFrench: "Je sais parler français.", exampleEnglish: "I know how to speak French." },
  { id: 'vb22', french: 'Prendre', english: 'To take', category: 'Action', exampleFrench: "Je prends le bus tous les jours.", exampleEnglish: "I take the bus every day." },
  { id: 'vb23', french: 'Venir', english: 'To come', category: 'Movement', exampleFrench: "Tu viens à la fête ce soir ?", exampleEnglish: "Are you coming to the party tonight?" },
  { id: 'vb24', french: 'Trouver', english: 'To find', category: 'Cognition', exampleFrench: "J'ai trouvé mes clés dans le sac.", exampleEnglish: "I found my keys in the bag." },
  { id: 'vb25', french: 'Donner', english: 'To give', category: 'Action', exampleFrench: "Elle me donne un cadeau.", exampleEnglish: "She is giving me a gift." },
  { id: 'vb26', french: 'Falloir', english: 'To be necessary', category: 'Modal', exampleFrench: "Il faut étudier pour l'examen.", exampleEnglish: "It is necessary to study for the exam." },
  { id: 'vb27', french: 'Devoir', english: 'To have to', category: 'Modal', exampleFrench: "Je dois partir maintenant.", exampleEnglish: "I have to leave now." },
  { id: 'vb28', french: 'Croire', english: 'To believe', category: 'Mental', exampleFrench: "Je crois qu'il va pleuvoir.", exampleEnglish: "I believe it's going to rain." },
  { id: 'vb29', french: 'Penser', english: 'To think', category: 'Mental', exampleFrench: "Je pense souvent à mes amis.", exampleEnglish: "I often think about my friends." },
  { id: 'vb30', french: 'Attendre', english: 'To wait', category: 'Action', exampleFrench: "Nous attendons le train sur le quai.", exampleEnglish: "We are waiting for the train on the platform." },
  { id: 'vb31', french: 'Arriver', english: 'To arrive', category: 'Movement', exampleFrench: "Le train arrive à l'heure.", exampleEnglish: "The train arrives on time." },
  { id: 'vb32', french: 'Partir', english: 'To leave', category: 'Movement', exampleFrench: "Nous partons en vacances demain.", exampleEnglish: "We are leaving on vacation tomorrow." },
  { id: 'vb33', french: 'Sortir', english: 'To go out', category: 'Movement', exampleFrench: "Tu sors avec nous ce soir ?", exampleEnglish: "Are you going out with us tonight?" },
  { id: 'vb34', french: 'Entendre', english: 'To hear', category: 'Senses', exampleFrench: "J'entends un bruit étrange.", exampleEnglish: "I hear a strange noise." },
  { id: 'vb35', french: 'Regarder', english: 'To look', category: 'Senses', exampleFrench: "Regarde cet oiseau bleu !", exampleEnglish: "Look at that blue bird!" },
  { id: 'vb36', french: 'Répondre', english: 'To answer', category: 'Communication', exampleFrench: "Il ne répond pas à ma question.", exampleEnglish: "He is not answering my question." },
  { id: 'vb37', french: 'Demander', english: 'To ask', category: 'Communication', exampleFrench: "Je demande le chemin pour la gare.", exampleEnglish: "I am asking for the way to the station." },
  { id: 'vb38', french: 'Devenir', english: 'To become', category: 'State', exampleFrench: "Il veut devenir médecin.", exampleEnglish: "He wants to become a doctor." },
  { id: 'vb39', french: 'Mettre', english: 'To put', category: 'Action', exampleFrench: "Mets ton manteau, il fait froid.", exampleEnglish: "Put on your coat, it's cold." },
  { id: 'vb40', french: 'Connaître', english: 'To know / be familiar with', category: 'Cognition', exampleFrench: "Je connais bien cette ville.", exampleEnglish: "I know this city well." },
];

export const CARDS_PER_GAME = 8;
